### ISSUE TITLE
Do input GWAS summary stats have to come from independent studies?

### ISSUE THREAD

**Issue by MalteThodberg** [clagiamba/moloc#1]
Do input summary statistics have to be independent?

I have done a GWAS for two related traits using the same samples: I would like to compare these results to known eQTL data. This means that the two GWAS tracks are not independent (done on the same samples).

Can MOLOC still be run in this use case?

**Comment by clagiamba** [comment]
Hi Malte,
Thank you for your interest in _moloc_!
Our manuscript refers to results for traits that are measured in unrelated individuals. 
However we do provide a function called 'adjust_bfs_overlap' and can be found here: https://github.com/clagiamba/moloc/blob/master/man/adjust_bfs_overlap.Rd

This function adjust ABFs for the overlaps using the expected correlation in betas due to correlation between the traits (there is a thorough and nice explanation in the gwas-pw paper). This function has been used in application of moloc, for example in Hatcher et al. PMID: 30820025. However, please keep in mind that the correlation with overlapping individuals was not tested via simulations in our manuscript, and all our results refer to association signals from non-overlapping individuals. 

Hope this helps and please feel free to contact me for any further questions.

**Comment by MalteThodberg** [comment]
Looking at this again!
Do you by any change have some example code for applying adjust_bfs_overlap()? Compare to a normal run of moloc_test()?

**Comment by clagiamba** [comment]
Hi Malte,

I had just tested the function - which is different when it computes the ABF at this stage:

ABF <- adjust_bfs_overlap(listData, prior_var = 0.15^2, overlap=TRUE, compute_sdY = FALSE, from_p = FALSE)

But I never tested applications of this and compared it to the normal run without correlations!
